project:
  type: website
  output-dir: docs

website:
  title: "Adam Coates"
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: cv/adamCoates_acdCV.pdf
        text: CV
      - icon: github
        href: https://github.com/adam-coates
      - href: contact.qmd
        text: Contact
  page-footer:
    background: light
    left:
      - "CC BY 4.0"
    right:
      - text: Contact
        href: contact.qmd
      - icon: github
        href: https://github.com/adam-coates
  back-to-top-navigation: true
  google-analytics: 
    tracking-id: G-0CBQ9T3TM7
    anonymize-ip: true
format:
  html:
    page-layout: full
    theme:
      light: 
        - flatly
        - main_theme.scss
      #flatly
      dark: 
        - darkly
        - dark_theme.scss
    highlight-style: a11y
    toc: true
editor: visual

