project:
  type: website
  output-dir: docs

website:
  title: "Adam Coates"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: cv/adamCoates_acdCV.pdf
        text: CV
      - icon: github
        href: https://github.com/adam-coates
      - icon: Uni Graz
        href: https://neurovision.uni-graz.at
  page-footer: 
    background: light
    left: 
      - "CC BY 4.0"
    right: 
      - icon: github
        href: https://github.com/adam-coates
format:
  html:
    page-layout: full
    theme: 
      light:  main_theme.scss
#flatly
      dark: dark_theme.scss
#    green_theme.scss
    toc: true

editor: visual

